### ISSUE TITLE
Bug: All payment types are being returned

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-48/bangazon-devinmgarcia#18]
When the client performs a GET request to the `/paymenttypes` resources, only the payment types added by the authenticated user should be returned.

Currently, all payment types in the system are being returned.

**Comment by heymonicakay** [comment]
Reopening as this issue is not yet resolved completely. When sending a GET request to `/paymenttypes`, the response contains payment types that do NOT belong to the authenticated user. Example: Steve has no payment types in the db. So, when I request `/paymenttypes` using Steve's token, I should get an empty array. However, instead I'm getting payment type 1, which actually belongs to Joe Shepherd. 

Please review and let me know when you've pushed up changes!

**Comment by devinmgarcia** [comment]
I believe I have fixed the issue
